package customerportal

object FilterFields extends Enumeration {

  type FilterFields = Value


val ICCID = ("iccid", "STRING_VALUE", true)
val LIMIT_STATE = ("limit_state", "LONG_VALUE", true, (0, 99, 99, 99))
val FRAUD_STATE = ("fraud_state", "LONG_VALUE", true, (0, 99, 99, 99))
val IMSI = ("imsi", "STRING_VALUE", true)
val IMEI = ("imei", "STRING_VALUE", true)
val EID = ("eid", "STRING_VALUE", true)
val MSISDN = ("msisdn", "STRING_VALUE", true)
val SIM_STATE = ("sim_state", "LONG_VALUE", true, (5))
val ORDER_ID = ("order_id", "LONG_VALUE", true)
val PROVIDER_ID = ("provider_id", "LONG_VALUE", false)
val PROVIDER_NAME = ("provider_name", "STRING_VALUE", true)
val SIM_TYPE = ("sim_type", "LONG_VALUE", false)
val SIM_TYPE_NAME = ("sim_type_name", "STRING_VALUE", true)
val SUBUNIT_ID = ("subunit_id", "LONG_VALUE", false)
val SUBUNIT = ("subunit", "STRING_VALUE", true)
val IP_ADDRESS = ("ip_address", "STRING_VALUE", false)
val VIRTUAL = ("virtual", "BOOLEAN_VALUE", false, (true, false))
val SCHEDULED_CHANGE = ("scheduled_change", "STRING_VALUE", false)
val SCHEDULED_CHANGE_DATE = ("scheduled_change_date", "DATE_VALUE", false)
val LAST_UPDATE = ("last_update", "DATE_VALUE", true)
val OFFERING_ID = ("offering_id", "LONG_VALUE", false)
val OFFERING_NAME = ("offering_name", "STRING_VALUE", true)
val DATA_PROFILE_ID = ("data_profile_id", "LONG_VALUE", false)
val DATA_PROFILE_NAME = ("data_profile_name", "STRING_VALUE", true)
val FRAUD_PROFILE_ID = ("fraud_profile_id", "LONG_VALUE", false)
val FRAUD_PROFILE_NAME = ("fraud_profile_name", "STRING_VALUE", true)
val BARRING_PROFILE_ID = ("network_profile_id", "LONG_VALUE", false)
val BARRING_PROFILE_NAME = ("network_profile_name", "STRING_VALUE", true)
val COSTLIMIT_PROFILE_ID = ("cost_limit_profile_id", "LONG_VALUE", false)
val COSTLIMIT_PROFILE_NAME = ("cost_limit_profile_name", "STRING_VALUE", true)
val LIMIT_PROFILE_ID = ("limit_profile_id", "LONG_VALUE", false)
val LIMIT_PROFILE_NAME = ("limit_profile_name", "STRING_VALUE", true)
val OPTION_IDS = ("option_ids", "STRING_VALUE", false)
val REMARK01 = ("remark01", "STRING_VALUE", true)
val REMARK02 = ("remark02", "STRING_VALUE", true)
val REMARK03 = ("remark03", "STRING_VALUE", true)
val REMARK04 = ("remark04", "STRING_VALUE", true)
val REMARK05 = ("remark05", "STRING_VALUE", true)
val REMARK06 = ("remark06", "STRING_VALUE", true)
val REMARK07 = ("remark07", "STRING_VALUE", true)
val REMARK08 = ("remark08", "STRING_VALUE", true)
val REMARK09 = ("remark09", "STRING_VALUE", true)
val REMARK10 = ("remark10", "STRING_VALUE", true)
}
